export const FETCH_TRANSACTION_INFO_START = 'FETCH_TRANSACTION_INFO_START';
export const FETCH_TRANSACTION_INFO_SUCCESS = 'FETCH_TRANSACTION_INFO_SUCCESS';
export const FETCH_TRANSACTIONS_INFO_FAILED = 'FETCH_TRANSACTIONS_INFO_FAILED';
